# validate the YAMl structure with: http://yaml-online-parser.appspot.com/
- route: "/{image_file}.{type: png|jpg|jpeg|txt}"
  method: get, head
  controller:
    name: ca.simplegames.micro.controllers.BinaryContent
    options: {
      mime_types: { .txt: "text/plain;charset=UTF-8" }
    }

- route: /system/info
  controller:
    name: ca.simplegames.micro.controllers.StatsController

- route: /logout
  controller:
    name: Logout.bsh
