filters:
  - before:
      controller: controllers.filters.Before
  - after:
      controller: controllers.filters.After

controllers:
  - controller:
      name: controllers.FindHotels  #beanshell will not work with ActiveJDBC