production:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://prod_server:3306/urls_production
  user: sa
  password:
  pool: 15

development:
  driver: org.h2.Driver
  url: jdbc:h2:WEB-INF/urls_development;AUTO_SERVER=TRUE
  user: sa
  password:
  pool: 5

test:
  driver: org.h2.Driver
  url: jdbc:h2:../urls_test;AUTO_SERVER=TRUE
  user: sa
  password:
  pool: 5
